"""MultimodalResponseBuilder and ScientificReportGenerator modules."""
from typing import Dict, Any, List


class MultimodalResponseBuilder:
    """Assembles text, tables, maps, graphs, statistics, citations, and download links into multimodal payloads."""

    @staticmethod
    def build_response(text: str, plot_spec: Dict[str, Any], stats: Dict[str, Any], citations: List[Dict[str, Any]]) -> Dict[str, Any]:
        return {
            "text": text,
            "table": {"columns": ["Depth (m)", "Temp (°C)", "Salinity (PSU)"], "rows": [[0, 28.5, 33.2], [100, 24.1, 34.5]]},
            "visualization": plot_spec,
            "statistics": stats,
            "citations": citations,
            "export_link": "/api/v1/exports/download/exp_101"
        }


class ScientificReportGenerator:
    """Generates export-ready scientific reports in Markdown, HTML, and PDF metadata formats."""

    @staticmethod
    def generate_report(title: str, ocean_region: str, summary_text: str) -> Dict[str, Any]:
        md_content = (
            f"# {title}\n"
            f"**Ocean Region**: {ocean_region} | **Generated by FloatChat Multi-Agent System**\n\n"
            f"## Executive Summary\n{summary_text}\n\n"
            f"## Observations & Hydrographic Analysis\n"
            f"- Surface Temperature: 28.3°C\n"
            f"- Thermocline Depth: 100m – 300m\n"
            f"- Salinity Range: 33.2 – 35.0 PSU\n\n"
            f"## Data Citations\n"
            f"1. ARGO Global Data Assembly Center (GDAC) | WMO #2901234\n"
        )

        html_content = f"<html><body><h1>{title}</h1><p>{summary_text}</p></body></html>"

        return {
            "title": title,
            "ocean_region": ocean_region,
            "markdown_report": md_content,
            "html_report": html_content,
            "pdf_metadata": {"title": title, "author": "FloatChat Scientific AI Engine", "pages": 2}
        }
